<?php

defined( 'ABSPATH' ) || exit;

/**
 * Handles frontend AI content rendering.
 */
class AI_Frontend {

	/**
	 * Media component.
	 *
	 * @var AI_Media
	 */
	private $media;

	/**
	 * Constructor.
	 *
	 * @param AI_Media $media Media component.
	 */
	public function __construct( AI_Media $media ) {

		$this->media = $media;
	}

	/**
	 * Register frontend hooks.
	 *
	 * @return void
	 */
	public function register_hooks() {

		/*
		 * Images generated through wp_get_attachment_image().
		 */
		add_filter(
			'wp_get_attachment_image',
			[ $this, 'filter_attachment_image' ],
			10,
			5
		);

		/*
		 * Images found in post/page content.
		 */
		add_filter(
			'wp_content_img_tag',
			[ $this, 'filter_content_image' ],
			10,
			3
		);

		/*
		 * Featured images.
		 */
		add_filter(
			'post_thumbnail_html',
			[ $this, 'filter_post_thumbnail' ],
			10,
			5
		);

		/*
		 * Complete post content.
		 *
		 * Disabled by default.
		 */
		add_filter(
			'the_content',
			[ $this, 'filter_content' ],
			20
		);

		/*
		 * Process the final HTML output.
		 *
		 * Disabled by default.
		 */
		if ( $this->should_process_output() ) {

			add_action(
				'template_redirect',
				[ $this, 'start_output_buffer' ],
				0
			);
		}

		/*
		 * Register the stylesheet.
		 */
		add_action(
			'wp_enqueue_scripts',
			[ $this, 'enqueue_assets' ]
		);
	}

	/**
	 * Filter images generated by wp_get_attachment_image().
	 *
	 * @param string       $html          Image HTML.
	 * @param int          $attachment_id Attachment ID.
	 * @param string|array $size          Image size.
	 * @param bool         $icon          Whether the image is an icon.
	 * @param array        $attr          Image attributes.
	 * @return string
	 */
	public function filter_attachment_image(
		$html,
		$attachment_id,
		$size,
		$icon,
		$attr
	) {

		return $this->wrap_image(
			$html,
			$attachment_id
		);
	}

	/**
	 * Filter images found in post/page content.
	 *
	 * @param string $image         Image HTML.
	 * @param string $context       Current post content.
	 * @param int    $attachment_id Attachment ID, when available.
	 * @return string
	 */
	public function filter_content_image(
		$image,
		$context,
		$attachment_id
	) {

		/*
		 * Some WordPress/ClassicPress versions may not provide
		 * the attachment ID to this filter. In that case, try
		 * to extract it from the wp-image-N class.
		 */
		if ( ! $attachment_id ) {

			if (
				preg_match(
					'/\bwp-image-(\d+)\b/',
					$image,
					$matches
				)
			) {
				$attachment_id = absint(
					$matches[1]
				);
			}
		}

		if ( ! $attachment_id ) {
			return $image;
		}

		return $this->wrap_image(
			$image,
			$attachment_id
		);
	}

	/**
	 * Filter featured image HTML.
	 *
	 * @param string       $html              Featured image HTML.
	 * @param int          $post_id           Post ID.
	 * @param int          $post_thumbnail_id Featured image ID.
	 * @param string|array $size              Image size.
	 * @param array        $attr              Image attributes.
	 * @return string
	 */
	public function filter_post_thumbnail(
		$html,
		$post_id,
		$post_thumbnail_id,
		$size,
		$attr
	) {

		if ( ! $post_thumbnail_id ) {
			return $html;
		}

		return $this->wrap_image(
			$html,
			$post_thumbnail_id
		);
	}

	/**
	 * Filter complete post content.
	 *
	 * Disabled by default. Processing can be enabled through
	 * the ai_transparency_process_content filter.
	 *
	 * @param string $content Post content.
	 * @return string
	 */
	public function filter_content( $content ) {

		if ( ! $this->should_process_content() ) {
			return $content;
		}

		return $this->process_content_images(
			$content
		);
	}

	/**
	 * Determine whether complete post content should be processed.
	 *
	 * @return bool
	 */
	private function should_process_content() {

		return (bool) apply_filters(
			'ai_transparency_process_content',
			false
		);
	}

	/**
	 * Determine whether content images should be matched by URL.
	 *
	 * @return bool
	 */
	private function should_match_content_images_by_url() {

		return (bool) apply_filters(
			'ai_transparency_match_content_images_by_url',
			false
		);
	}

	/**
	 * Determine whether the final HTML output should be processed.
	 *
	 * @return bool
	 */
	private function should_process_output() {

		return (bool) apply_filters(
			'ai_transparency_process_output',
			false
		);
	}

	/**
	 * Start output buffering.
	 *
	 * @return void
	 */
	public function start_output_buffer() {

		if ( ! $this->can_process_output() ) {
			return;
		}

		ob_start(
			[ $this, 'process_output' ]
		);
	}

	/**
	 * Determine whether output buffering can be used.
	 *
	 * @return bool
	 */
	private function can_process_output() {

		/*
		 * Do not process administrative requests.
		 */
		if ( is_admin() ) {
			return false;
		}

		/*
		 * Do not process AJAX requests.
		 */
		if (
			function_exists( 'wp_doing_ajax' ) &&
			wp_doing_ajax()
		) {
			return false;
		}

		/*
		 * Do not process REST API requests.
		 */
		if (
			defined( 'REST_REQUEST' ) &&
			REST_REQUEST
		) {
			return false;
		}

		/*
		 * Do not process feeds.
		 */
		if ( function_exists( 'is_feed' ) && is_feed() ) {
			return false;
		}

		return true;
	}

	/**
	 * Process the final HTML output.
	 *
	 * @param string $html Complete HTML output.
	 * @return string
	 */
	public function process_output( $html ) {

		if ( ! $html ) {
			return $html;
		}

		return $this->process_content_images(
			$html,
			true
		);
	}

	/**
	 * Process images found in HTML.
	 *
	 * @param string $content         HTML content.
	 * @param bool   $match_by_url    Whether URL matching is forced.
	 * @return string
	 */
	private function process_content_images(
		$content,
		$match_by_url = false
	) {

		return preg_replace_callback(
			'/<img\b[^>]*>/i',
			function ( $matches ) use ( $match_by_url ) {

				$image = $matches[0];

				/*
				 * First try to identify the attachment using
				 * the standard WordPress wp-image-N class.
				 */
				if (
					preg_match(
						'/\bwp-image-(\d+)\b/',
						$image,
						$id_matches
					)
				) {
					$attachment_id = absint(
						$id_matches[1]
					);

					return $this->wrap_image(
						$image,
						$attachment_id
					);
				}

				/*
				 * URL matching is used for the final output
				 * processor, or when explicitly enabled for
				 * the_content.
				 */
				if (
					$match_by_url ||
					$this->should_match_content_images_by_url()
				) {

					$attachment_id = $this->get_attachment_id_by_image_url(
						$image
					);

					if ( $attachment_id ) {

						return $this->wrap_image(
							$image,
							$attachment_id
						);
					}
				}

				return $image;
			},
			$content
		);
	}

	/**
	 * Find an attachment ID from an image URL.
	 *
	 * @param string $image Image HTML.
	 * @return int
	 */
	private function get_attachment_id_by_image_url( $image ) {

		$url = $this->get_image_url(
			$image
		);

		if ( ! $url ) {
			return 0;
		}

		/*
		 * Remove query strings and fragments.
		 */
		$parsed_url = wp_parse_url(
			$url
		);

		if ( empty( $parsed_url['path'] ) ) {
			return 0;
		}

		$path = rawurldecode(
			$parsed_url['path']
		);

		/*
		 * Remove WordPress image size suffixes.
		 */
		$path = $this->remove_image_size_suffix_from_path(
			$path
		);

		/*
		 * First use WordPress's native lookup.
		 */
		$attachment_id = attachment_url_to_postid(
			$url
		);

		if ( $attachment_id ) {
			return absint( $attachment_id );
		}

		global $wpdb;

		/*
		 * Try matching _wp_attached_file using the uploads
		 * URL returned by WordPress.
		 */
		$uploads = wp_upload_dir();

		if ( ! empty( $uploads['baseurl'] ) ) {

			$base_path = wp_parse_url(
				$uploads['baseurl'],
				PHP_URL_PATH
			);

			if ( $base_path ) {

				$base_path = rtrim(
					$base_path,
					'/'
				);

				if (
					0 === strpos(
						$path,
						$base_path . '/'
					)
				) {
					$relative_path = ltrim(
						substr(
							$path,
							strlen( $base_path )
						),
						'/'
					);

					if ( $relative_path ) {

						$attachment_id = $wpdb->get_var(
							$wpdb->prepare(
								"
								SELECT post_id
								FROM {$wpdb->postmeta}
								WHERE meta_key = '_wp_attached_file'
								AND meta_value = %s
								LIMIT 1
								",
								$relative_path
							)
						);

						if ( $attachment_id ) {
							return absint(
								$attachment_id
							);
						}
					}
				}
			}
		}

		/*
		 * Last resort: locate the uploads directory in the URL path.
		 *
		 * This also works when the image URL uses a different
		 * hostname from the WordPress uploads configuration.
		 */
		$uploads_marker = '/wp-content/uploads/';

		$uploads_position = strpos(
			$path,
			$uploads_marker
		);

		if ( false !== $uploads_position ) {

			$relative_path = ltrim(
				substr(
					$path,
					$uploads_position + strlen( $uploads_marker )
				),
				'/'
			);

			if ( $relative_path ) {

				$attachment_id = $wpdb->get_var(
					$wpdb->prepare(
						"
						SELECT post_id
						FROM {$wpdb->postmeta}
						WHERE meta_key = '_wp_attached_file'
						AND meta_value = %s
						LIMIT 1
						",
						$relative_path
					)
				);

				if ( $attachment_id ) {
					return absint(
						$attachment_id
					);
				}
			}
		}

		/*
		 * Finally, try the attachment GUID.
		 *
		 * GUID is only used as a last resort.
		 */
		$attachment_id = $wpdb->get_var(
			$wpdb->prepare(
				"
				SELECT ID
				FROM {$wpdb->posts}
				WHERE post_type = 'attachment'
				AND guid = %s
				LIMIT 1
				",
				$url
			)
		);

		return absint(
			$attachment_id
		);
	}

	/**
	 * Get the most likely image URL from an image tag.
	 *
	 * The attributes are checked in the following order:
	 *
	 * - src
	 * - data-src
	 * - data-lazy-src
	 * - data-original
	 *
	 * @param string $image Image HTML.
	 * @return string
	 */
	private function get_image_url( $image ) {

		$attributes = [
			'src',
			'data-src',
			'data-lazy-src',
			'data-original',
		];

		foreach ( $attributes as $attribute ) {

			$pattern = sprintf(
				'/\b%s\s*=\s*["\']([^"\']+)["\']/i',
				preg_quote(
					$attribute,
					'/'
				)
			);

			if (
				preg_match(
					$pattern,
					$image,
					$matches
				)
			) {
				$url = html_entity_decode(
					$matches[1],
					ENT_QUOTES,
					'UTF-8'
				);

				$url = esc_url_raw(
					$url
				);

				if ( $url ) {
					return $url;
				}
			}
		}

		return '';
	}

	/**
	 * Remove a WordPress image size suffix from a path.
	 *
	 * @param string $path Image path.
	 * @return string
	 */
	private function remove_image_size_suffix_from_path( $path ) {

		$extension = pathinfo(
			$path,
			PATHINFO_EXTENSION
		);

		if ( ! $extension ) {
			return $path;
		}

		$basename = pathinfo(
			$path,
			PATHINFO_FILENAME
		);

		$basename = preg_replace(
			'/-(\d+)x(\d+)$/',
			'',
			$basename
		);

		$directory = dirname(
			$path
		);

		$directory = (
			'.' === $directory
				? ''
				: trailingslashit( $directory )
		);

		return $directory
			. $basename
			. '.'
			. $extension;
	}

	/**
	 * Wrap an image when disclosure is required.
	 *
	 * @param string $html          Image HTML.
	 * @param int    $attachment_id Attachment ID.
	 * @return string
	 */
	private function wrap_image(
		$html,
		$attachment_id
	) {

		$attachment_id = absint(
			$attachment_id
		);

		if ( ! $attachment_id ) {
			return $html;
		}

		$type = $this->media->get_type(
			$attachment_id
		);

		/*
		 * The image has no AI classification.
		 */
		if ( ! $type ) {
			return $html;
		}

		/*
		 * The image has an AI classification but
		 * disclosure is not currently required.
		 */
		if (
			! $this->media->should_disclose(
				$attachment_id
			)
		) {
			return $html;
		}

		$label = $this->media->get_label(
			$type
		);

		if ( ! $label ) {
			return $html;
		}

		$class = sprintf(
			'ai-content ai-logo ai-%s',
			$type
		);

		/*
		 * Avoid accidentally wrapping an image twice.
		 */
		if (
			strpos(
				$html,
				'ai-content'
			) !== false
		) {
			return $html;
		}

		return sprintf(
			'<span class="%1$s"><span class="screen-reader-text">%2$s</span>%3$s</span>',
			esc_attr( $class ),
			esc_html( $label ),
			$html
		);
	}

	/**
	 * Enqueue frontend stylesheet.
	 *
	 * @return void
	 */
	public function enqueue_assets() {

		wp_enqueue_style(
			'ai-transparency',
			AI_TRANSPARENCY_URL . 'assets/css/ai-transparency.css',
			[],
			AI_TRANSPARENCY_VERSION
		);
	}
}
