<?php

defined( 'ABSPATH' ) || exit;

/**
 * Handles frontend AI content rendering.
 */
class AI_Frontend {

	/**
	 * Media component.
	 *
	 * @var AI_Media
	 */
	private $media;

	/**
	 * Constructor.
	 *
	 * @param AI_Media $media Media component.
	 */
	public function __construct( AI_Media $media ) {

		$this->media = $media;
	}

	/**
	 * Register frontend hooks.
	 *
	 * @return void
	 */
	public function register_hooks() {

		/*
		 * Images generated through wp_get_attachment_image().
		 */
		add_filter(
			'wp_get_attachment_image',
			[ $this, 'filter_attachment_image' ],
			10,
			5
		);

		/*
		 * Images found in post/page content.
		 */
		add_filter(
			'wp_content_img_tag',
			[ $this, 'filter_content_image' ],
			10,
			3
		);

		add_filter(
			'post_thumbnail_html',
			[ $this, 'filter_post_thumbnail' ],
			10,
			5
		);

		/*
		 * Register the stylesheet.
		 */
		add_action(
			'wp_enqueue_scripts',
			[ $this, 'enqueue_assets' ]
		);
	}

	/**
	 * Filter featured image HTML.
	 *
	 * @param string       $html          Featured image HTML.
	 * @param int          $post_id       Post ID.
	 * @param int          $post_thumbnail_id Featured image ID.
	 * @param string|array $size          Image size.
	 * @param array        $attr          Image attributes.
	 * @return string
	 */
	public function filter_post_thumbnail(
		$html,
		$post_id,
		$post_thumbnail_id,
		$size,
		$attr
	) {

		if ( ! $post_thumbnail_id ) {
			return $html;
		}

		return $this->wrap_image(
			$html,
			$post_thumbnail_id
		);
	}

	/**
	 * Filter images generated by wp_get_attachment_image().
	 *
	 * @param string       $html          Image HTML.
	 * @param int          $attachment_id Attachment ID.
	 * @param string|array $size          Image size.
	 * @param bool         $icon          Whether the image is an icon.
	 * @param array        $attr          Image attributes.
	 * @return string
	 */
	public function filter_attachment_image(
		$html,
		$attachment_id,
		$size,
		$icon,
		$attr
	) {

		return $this->wrap_image(
			$html,
			$attachment_id
		);
	}

	/**
	 * Filter images found in post/page content.
	 *
	 * WordPress normally adds a class such as:
	 *
	 * wp-image-123
	 *
	 * to images inserted through the Media Library.
	 *
	 * @param string  $image   Image HTML.
	 * @param string  $context Current post content.
	 * @param int     $attachment_id Attachment ID, when available.
	 * @return string
	 */
	public function filter_content_image(
		$image,
		$context,
		$attachment_id
	) {

		/*
		 * Some WordPress/ClassicPress versions may not provide
		 * the attachment ID to this filter. In that case, try
		 * to extract it from the wp-image-N class.
		 */
		if ( ! $attachment_id ) {

			if (
				preg_match(
					'/\bwp-image-(\d+)\b/',
					$image,
					$matches
				)
			) {
				$attachment_id = absint(
					$matches[1]
				);
			}
		}

		if ( ! $attachment_id ) {
			return $image;
		}

		return $this->wrap_image(
			$image,
			$attachment_id
		);
	}

	/**
	 * Wrap an image when disclosure is required.
	 *
	 * @param string $html          Image HTML.
	 * @param int    $attachment_id Attachment ID.
	 * @return string
	 */
	private function wrap_image(
		$html,
		$attachment_id
	) {

		$attachment_id = absint(
			$attachment_id
		);

		if ( ! $attachment_id ) {
			return $html;
		}

		$type = $this->media->get_type(
			$attachment_id
		);

		/*
		 * The image has no AI classification.
		 */
		if ( ! $type ) {
			return $html;
		}

		/*
		 * The image has an AI classification but
		 * disclosure is not currently required.
		 */
		if (
			! $this->media->should_disclose(
				$attachment_id
			)
		) {
			return $html;
		}

		$label = $this->media->get_label(
			$type
		);

		if ( ! $label ) {
			return $html;
		}

		$class = sprintf(
			'ai-content ai-logo ai-%s',
			$type
		);

		/*
		 * Avoid accidentally wrapping an image twice.
		 */
		if (
			strpos(
				$html,
				'ai-content'
			) !== false
		) {
			return $html;
		}

		return sprintf(
			'<span class="%1$s"><span class="screen-reader-text">%2$s</span>%3$s</span>',
			esc_attr( $class ),
			esc_html( $label ),
			$html
		);
	}

	/**
	 * Enqueue frontend stylesheet.
	 *
	 * @return void
	 */
	public function enqueue_assets() {

		wp_enqueue_style(
			'ai-transparency',
			AI_TRANSPARENCY_URL . 'assets/css/ai-transparency.css',
			[],
			AI_TRANSPARENCY_VERSION
		);
	}
}
